### ISSUE TITLE
UI needs way of displaying warning on individual migration

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#810]
The checksum validation failure will arise as a warning on the MigMigration. As far as I'm aware, there is not currently UI support for displaying this warning. @sseago if you'd like to add anything to this please do.

**Comment by sseago** [comment]
There are two possible warning conditions right now to look for on the MigMigration. `type: ResticErrors` for overall (non-fatal) errors with restic, and `type: ResticVerifyErrors` for verify-specific errors. The latter is a subset of the former. 

Here's an example of a ResticError warning:
```
status:
  conditions:
  - category: Warn
    durable: true
    lastTransitionTime: 2020-04-16T20:35:16Z
    message: There were errors found in 1 Restic volume restores. See restore `registry-example-migration-p8t42`
      for details
    status: "True"
    type: ResticErrors
```
Here's an example of a ResticVerifyError warning:
```
status:
  conditions:
  - category: Warn
    durable: true
    lastTransitionTime: 2020-04-16T20:35:16Z
    message: There were verify errors found in 1 Restic volume restores. See restore `registry-example-migration-p8t42`
      for details
    status: "True"
    type: ResticVerifyErrors
```
